
services:
  db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD:
      # MYSQL_DATABASE: mydb
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql